services:
  # -----------------------------------------------------------
  # M2. CatalogService (Catálogo de Libros)
  # -----------------------------------------------------------
  db-catalog:
    image: mysql:8.0
    container_name: db_catalog
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_catalog:/var/lib/mysql
# ----------------------------------------------------------------------
  catalog-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: catalog-service-container
    ports:
      - "8081:8081"
    depends_on:
      - db-catalog
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./catalog-service-code/catalog-service:/app
    working_dir: /app

  # -----------------------------------------------------------
  # M3. InventoryService (Catálogo de Libros)
  # -----------------------------------------------------------
  db-inventory:
    image: mysql:8.0
    container_name: db_inventory
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_inventory:/var/lib/mysql
# ----------------------------------------------------------------------
  inventory-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: inventory-service-container
    ports:
      - "8082:8082"
    depends_on:
      - db-inventory
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./inventory-service-code/inventory-service:/app
    working_dir: /app

  # -----------------------------------------------------------
  # M4. CartService (Gestión de Carrito de Compras)
  # -----------------------------------------------------------
  db-cart:
    image: mysql:8.0
    container_name: db_cart
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: cart_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_cart:/var/lib/mysql
# ----------------------------------------------------------------------
  cart-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: cart-service-container
    ports:
      - "8083:8083"
    depends_on:
      - db-cart
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./cart-service-code/cart-service:/app
    working_dir: /app

  # -----------------------------------------------------------
  # M5. OrderService (Gestión de Ordenes de Compra)
  # -----------------------------------------------------------
  db-order:
    image: mysql:8.0
    container_name: db_order
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: order_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_order:/var/lib/mysql
# ----------------------------------------------------------------------
  order-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: order-service-container
    ports:
      - "8084:8084"
    depends_on:
      - db-order
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./order-service-code/order-service:/app
    working_dir: /app

  # -----------------------------------------------------------
  # MICROSERVICIO 9: ReviewService (Valoraciones y Comentarios)
  # -----------------------------------------------------------
  db-review:
    image: mysql:8.0
    container_name: db_review
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: review_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_review:/var/lib/mysql
    # ----------------------------------------------------------------------
  review-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: review-service-container
    ports:
      - "8088:8088"
    depends_on:
      - db-review
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./review-service-code/review-service:/app
    working_dir: /app

networks:
  red_interna_proyecto:

volumes:
  persistencia_catalog:
  persistencia_review:
  persistencia_inventory:
  persistencia_cart:
  persistencia_order:

