services:
  # -----------------------------------------------------------
  # BASE DE DATOS: Compartida por toda la librería
  # -----------------------------------------------------------
  db-servicio:
    image: mysql:8.0
    container_name: mysql_servidor
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: universidad_backend
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3306:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_db:/var/lib/mysql

  # -----------------------------------------------------------
  # MICROSERVICIO 2: CatalogService (Catálogo de Libros)
  # -----------------------------------------------------------
  catalog-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: catalog_service_container
    ports:
      - "8080:8080"
    depends_on:
      - db-servicio
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./catalog-service-code:/app
    working_dir: /app

  # -----------------------------------------------------------
  # MICROSERVICIO 9: ReviewService (Valoraciones y Comentarios)
  # -----------------------------------------------------------
  review-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: review_service_container
    ports:
      - "8081:8081"
    depends_on:
      - db-servicio
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./review-service-code:/app
    working_dir: /app

networks:
  red_interna_proyecto:

volumes:
  persistencia_db:
