services:
  # -----------------------------------------------------------
  # M2. CatalogService (Catálogo de Libros)
  # -----------------------------------------------------------
  db-catalog:
    image: mysql:8.0
    container_name: db_catalog
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_catalog:/var/lib/mysql

  catalog-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: catalog-service-container
    ports:
      - "8081:8081"
    depends_on:
      - db-catalog
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./catalog-service-code/catalog-service:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_catalog:3306/catalog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=desarrollador
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123

  # -----------------------------------------------------------
  # M3. InventoryService (Inventario/Stock)
  # -----------------------------------------------------------
  db-inventory:
    image: mysql:8.0
    container_name: db_inventory
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_inventory:/var/lib/mysql

  inventory-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: inventory-service-container
    ports:
      - "8082:8082"
    depends_on:
      - db-inventory
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./inventory-service-code/inventory-service:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_inventory:3306/inventory_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=desarrollador
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123
      # Comunicación Feign interna (Usa el container_name del catálogo)
      - CATALOG_SERVICE_URL=http://catalog-service-container:8081

  # -----------------------------------------------------------
  # M4. CartService (Gestión de Carrito de Compras)
  # -----------------------------------------------------------
  db-cart:
    image: mysql:8.0
    container_name: db_cart
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: cart_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_cart:/var/lib/mysql

  cart-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: cart-service-container
    ports:
      - "8083:8083"
    depends_on:
      - db-cart
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./cart-service-code/cart-service:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_cart:3306/cart_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=desarrollador
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123
      # El carrito mira al catálogo y al inventario dentro de tu misma red
      - CATALOG_SERVICE_URL=http://catalog-service-container:8081
      - INVENTORY_SERVICE_URL=http://inventory-service-container:8082
      - USERS_URL=http://44.196.219.155:8080

  # -----------------------------------------------------------
  # M5. OrderService (Gestión de Ordenes de Compra)
  # -----------------------------------------------------------
  db-order:
    image: mysql:8.0
    container_name: db_order
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: order_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_order:/var/lib/mysql

  order-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: order-service-container
    ports:
      - "8084:8084"
    depends_on:
      - db-order
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./order-service-code/order-service:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_order:3306/order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=desarrollador
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123
      # La orden necesita comunicarse con tu carrito local
      - CART_SERVICE_URL=http://cart-service-container:8083
      
      - USERS_URL=http://44.196.219.155:8080

  # -----------------------------------------------------------
  # MICROSERVICIO 9: ReviewService (Valoraciones y Comentarios)
  # -----------------------------------------------------------
  db-review:
    image: mysql:8.0
    container_name: db_review
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: review_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_review:/var/lib/mysql

  review-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: review-service-container
    ports:
      - "8088:8088"
    depends_on:
      - db-review
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./review-service-code/review-service:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_review:3306/review_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=desarrollador
      - SPRING_DATASOURCE_PASSWORD=password_seguro_123

      - CATALOG_SERVICE_URL=http://catalog-service-container:8081

      - USERS_URL=http://44.196.219.155:8080

networks:
  red_interna_proyecto:
    driver: bridge

volumes:
  persistencia_catalog:
  persistencia_review:
  persistencia_inventory:
  persistencia_cart:
  persistencia_order: